---
title: "Methods"
editor_options: 
  chunk_output_type: console
bibliography: paper2.bib
link-citations: true
csl: entomological-society-of-america-2.csl
# suppress-bibliography: true
---

## Plant Culture {.unnumbered}

Smooth brome was grown from transplanted plants harvested from the Arthur H. Post Agronomy Farm (43°38'19.39" N, 116°14'28.86" W). Immediately following collection, plants were transplanted into 2.7 x 14 inch lightweight deepot cells (Stuewe & Sons Inc®, Tangent, OR) and moved into greenhouse space at Montana State University's Plant Growth Center. Wheat was grown using ‘Yellowstone’ winter wheat cultivar seed stock, started in 1 x 8 inch conical pots. The soil used consisted of MSU Plant Growth Center soil mix (equal parts sterilized Bozeman silt loam soil and washed concrete sand with Canadian sphagnum peat moss incorporated) and Sunshine Mix 1 (Canadian sphagnum peat moss, vermiculite, perlite, and Dolomite lime) in a 1:1 ratio. Fertilization was undergone once weekly using Jack’s Professional® Water-Soluble Fertilizer (20-20-20) (J.R. Peters Inc., Allentown, PA). Supplemental light from model MVR1000/C/U GE Multi-Vapor Lamps (GE Lighting, General Electric Company, Cleveland, OH) under photoperiod of 16:8 (L:D) h at 22 \pm 2°C and 20 – 40 % RH. After the wheat plants reached Zadoks 12, they were moved into vernalization storage for 6 weeks to experience the length of dormancy needed for successful flower development.  After the six-week period, stems were transplanted into the larger, 2.7 x 14-inch conical pots. 


## Insects

Wheat stubble collected the year prior to each experiment were used to rear adult WSS. Wheat stubble was collected from Big Sandy (48°10'39.14" N, 110°6'50.62" W) and Three Forks (45°59'33.38" N, 111°37'7.42" W), MT. Stubble was collected from fields that experienced high levels of WSS infestation and cutting the year prior. Cut stubble, which contained WSS larvae in diapause, were kept in a refrigerator between 0-4°C for >100 days as required to complete obligatory larval diapause. After completing diapause, immature WSS were kept at room temperature between 22-27°C for 4-5 weeks in sealed 70 cm x 35 cm x 20 cm plastic Tupperware® bins to allow for pupation and emergence. Once emergence began, adults were collected daily and sorted in 2-liter glass mason jars sealed with filter paper to allow for airflow. Jars containing adults were refrigerated at 6-10°C until they were needed for experiments. Unused adults were discarded after 48 hours of refrigeration. 

Wheat stem residue containing parasitoids *B. cephi* and *B. lissogaster* were collected from wheat fields in Three Forks, MT (46°1'12.78" N, 111°35'11.70" W). Fields were selected that experienced high levels of WSS infestation. Stem residue was collected and stored inside 170-liter plastic barrel liners and stored in a cold storage room at 4°C until mid or late spring of the following year to provide enough time for the insects to complete obligatory diapause. Plastic barrel liners were then removed from cold storage and the residue placed inside 170-liter trash barrels at room temperature and watered to encourage larval development and emergence. Parasitoids were collected daily as they emerged kept at 6-10°C until used. 

## Greenhouse Infestation

Winter wheat and smooth brome plants were infested when at similar stages. Winter wheat plants were deemed ready for infestation once they reached Zadoks 49. Methods were adopted from Biyiklioglu et al., 2018. Briefly, plants were infested by placing a transparent plastic cylinder (60 x 3.8 cm) over the main stem of the plant. A 55-60 cm bamboo stick was added within each tube to help prevent toppling of the cylinder. Each cage had three holes, as well as an open top, covered with fine 530 µM mesh cloth to allow for air circulation. Four females and two male WSS, newly emerged, were introduced into each tube via a small 1 cm opening. After which, the hole was plugged using a cotton ball covered in mesh cloth. Damp 50-50 mix soil was mounded around the base of each tube to prevent insect escape. Adult sawflies were left within infestation tubes for three days, during which the plants were not watered or fertilized. After the three days, the tubes were removed, and any surviving insects, as well as cadavers, were removed. Thee plants were then returned to normal water and fertilization schedules. 

Infestation was undertaken three days a week, for five weeks. Each replicate included 6 ‘Yellowstone’ winter wheat plants at Zadoks 49 and 6 smooth brome plants exhibiting three nodes. For each replicate, four wheat and four smooth brome plants were infested, with two of each left uninfested as controls. Infestation tubes were placed around all twelve plants for each replicate. 

## Volatile Organic Compound Collection

Volatile compounds were collected from intact and healthy smooth brome and ‘Yellowstone’ winter wheat. Collection was undergone on plants at Zadoks 49 - approximately 6 weeks after infestation, for a period of six hours from 09:00 to 15:00. Collections were undergone three times a week, with twelve plants collected from each time. Each trail consisted of six smooth brome plants and six winter wheat, with three of each being infested, while the other three were a control. 

Volatiles were collected from twelve plants per day using glass volatile collection chambers (VCC) that were 80 cm long and 4 cm in diameter. Volatile collection and successive GC-MS analysis were conducted following methods described in Weaver et al. (2009). The top end of each VCC funneled into a threaded port that was 10 cm in diameter. Threaded onto the top of each VCC was an eight-port manifold adapter. Two glass filters (traps) (6.35 mm diameter x 76 mm length; Analytical Research Systems, Gainesville, FL) with 30 mg of Super-Q absorbent (Alltech Associates, Deerfield, IL) were inserted into two of the adapter ports. The remaining six collection ports were sealed to prevent ambient air exchange and pressure loss. One of the traps was used to collected extraneous volatiles from the initial experiment set up for the first ten minutes, whereas the other trap was used to collect volatile compounds emanating from plants beginning ten minutes after the system was turned on. A 24/210 threaded glass joint at the base of each VCC was connected to an teflon tubing that pumped in charcoal-filtered and humidified air pressure regulated by a diaphragm air pump, delivering air at a rate of 0.2 L min$^{-1}$. A vacuum pump was connected via teflon tubing to each of the traps to maintain air pressure and flow rate (humidified air at 1.0 liter/min) within the collection system. A Teflon guillotine was used at the base of each plant to tightly seal the base of the system and prevent external air from entering. Each plant stem was wrapped with a small piece of cotton prior to the application of the guillotine to further seal the base of the collection system and prevent contamination by ambient and soil derived volatiles.  

After the completion of volatile collection, VOCs were eluted from the glass traps using 200 µL aliquot dichloromethane. Trapped volatiles were eluted slowly by adding dichloromethane and further clearing by using a slow release of nitrogen gas. The eluted samples were collected in a glass insert held within a 1.5-mL crimped top glass vial. 10 µL of nonyl acetate were then added to the eluted samples as internal standard to aid in quantification of compound concentrations. The samples were processed using gas chromatography (GC) on a HP - 5MS; 30m x 0.25mm, 0.25 µm film thickness column (J and W Scientific, Folsom, CA). To analyze, the GC instrument (Agilent 6890; Agilent Technologies, Inc., Santa Clara, CA) was coupled to a mass spectrometer (MS, Agilent 5973 instrument). Each sample was injected using the automated system in pulse splitless mode, with the initial pressure set to 82.7 kPa per minute. The inlet temperature of the GC was set to 250°C while the column temperature was 50°C for 4 minutes. The temperature was set to increase at a rate of 5°C per minute until it reached 160°C, after which it increased to a rate of 25°C per minute until it reached 280°C. The temperature of the transfer line leading to the mass selective detector (MSD) was set at 300°C. Helium was used as a carrier gas to maintain the flow rate of samples within the column at 1.2 mL/min. The MSD was set in ‘SCAN’ mode running from 50 – 300 m/z. 

The compounds collected from both the smooth brome and wheat samples were identified by comparing mass spectra and retention times using the National Institute of Standard and Technology (NIST) library. Peaks and volatiles were analyzed using MSD ChemStation (Agilent Technologies, Inc., Santa Clara, CA). The true quantity of compounds was calculated relative to the internal standard. 

## Behavioral Assessment of Parasitoids in Response to Volatile Organic Compounds

### Electroantennography & Flame Ionization Detection 

To test for response to compounds in smooth brome and winter wheat, we coupled eletroantennographic detection with a flame ionization detector (EAD-FID). Adult female *Bracon* spp parasitoids were prepared by excising the head from the body using fine micro-dissection scissors. For each specimen, The parasitoid head was mounted on a flat electrode supplemented with a small amount of electrode gel (Spectra 360, Parker Laboratories, Inc., Farfield, NJ) to facilitate electrical conductivity. The electrode was connected to a Type INR-5 micromanipulator (Narishige MN-151, Narishige International USA, Inc., Amityville, NY). The second electrode was also coated with electrode gel and connected to teh second insertion point. One of the subject's antennae of the parasitoid was manipulated to make contact with the second electrode, thereby completing the circuit. This apparatus and method has been consistently used previously in assessing insect volatile response [@Agelopoulos1999]. Purified, humidified air (20 mL sec-1) was supplied consistently onto the antennae. The amplifier transferred the information to a computer interface with an EAG version 2.7 software (Syntech NL 2001, Hilversum, Netherlands). 

EAD equipment was coupled to a flame ionization detector (FID, Agilent) to test for electroantennal response to volatile stimuli. Volatile samples were run through FID (6890N, Agilent Technologies, Inc., Santa Clara, CA) using a 30 m, 250 µm Agilent J&W column. Each sample was injected using the automated system in pulsed splitless mode, with the internal pressure set to 11.8 kPa. The initial oven temperature of the FID was held at 50°C for 4 minutes, after which it was increased by 15°C/min until the final temperature of 160°C was reached. The inlet temperature of the FID was set to 250°C with hydrogen flow set to 35 ml/min. Nitrogen was used as the makeup gas and set to a flow rate of 40  ml/min and a pressure of 400 kPa. Air flow was set to 450 ml/min with a pressure of 550 kPa. 

Once a run was triggered, both FID output and EAD responses were recorded using EAD Plus (EAD, Santa Clara, CA). Results were expoerted to R

## Y-Tube Olfactometer Bioassay

Bioassays were conducted to assess variation in behavioral responses of naive female parasitoids to both winter wheat and smooth brome volatiles. Volatiles were a combined mixture of 15-20 collected volatile samples from our volatile collection experiment. We combined volatiles from infested plants and used them to mimic the volatile signature of infested plants. 

We used a Y-Tube system (Analytical Research Systems, Micanopy, FL) similar to those used by Daisy et al. (2002). Y-tubes consisted of Corning glass tube (28-mm diameter x 300 mm long) that branched at 20-cm along a 120° angle to form the arm of each tube. Each arm extended 3 cm from the junction before becoming parallel, with a total length of 10 cm for each parallel section. Each arm was connected to a diaphragm air pump that delivered charcoal-filtered and humidified air ata  rate of 0.2 l/min. 50 ul of extracted volatile mixture was pipetted onto a small piece of filter paper and placed inside a 46 cm Corning tube with a ground-glass joint at one end to connect to the Y-Tube, and a threaded-glass joint to receive the air supply. Two of these tubes were used for each trial. Y-tubes were used for a single trial before being exchanged for a fresh, clean tube.  

For each assay, a single naïve female *B. cephi* or *B. lissogaster* parasitoid was introduced 1 cm into the unbranched end of the Y-tube. To facilitate female parasitoid movement toward the Y-tube junction, black box containing Y-tube was angled at a 10° angle with the 'Y' end elevated. In addition, a 28-cm long metal wire was placed on the unbranched portion of the Y-tube, spaning the length from the introduction point to the branch). Females were placed insid teh Y-tube on the top of the wire, 3-cm from the introduction point. Individuals were randomly assigned to each assay, and discarded after assay completion. Females were observed for 2-minutes, with the trial ending when a choice was made, or when no response was observed (recorded as non-responders). We used a total of 58 *B. cephi* and 68 *B. lissogaster* were used during the trials. 

After each assay, glassware was cleaned using a non-foaming anionic Liquinox detergent (Alconox Inc., White Plains, NY) in warm water, rinsed with water, and rinsed with the solvents acetone and hexane. Glassware was then placed in a 110 °C oven and baked for a minimum of 2 hours before the next use. 




Y- Tube Olfactometer Bioassay
Y-tube bioassays were conducted within the chemical ecology and insect behavior laboratory at the Plant Growth Center at Montana State University. Bioassays were undergone to determine behavioral choice preference response of individual female WSS to an airstream containing volatiles originating from smooth brome and a blank control. Bioassays were conducted using plants at growth stage Zadoks 49. The Y-tube system (Analytical Rsearch Systems, Micanopy, FL) used was similar as described in a previous study (Daisy et al., 2002) (Figure 1). A single plant was enclosed in a volatile collection chamber (VCC) (100 mm diameter, 254 mm length). Input air was charcoal-filtered and humidified, regulated by a diaphragm air pump that delivered air at a rate of 0.2 L min-1. Air was moved into the VCC through Teflon tubing connected with a 24/410 threaded glass joint. The bottom end of the VCC enclosed each plant and was tightly sealed by a Teflon guillotine (diameter 955 mm, 15 mm center opening), encircling the stem to prevent air leakage. The olfactory system used a Y-shaped glass tube that had two arms connected to the lower port of each VCC by Teflon tubing (diameter 0.64 cm), providing the airstream source from the plant. The VCC contained plant was illuminated by an enhanced spectrum LED grow light (sunshine Systems Grow UFO Light SS-Gu90w, Led Lighting4 Less, Paradise, CA) for one hour before the experiment to make the plant photosynthetically active. 

The Y-tube was made of bifurcated Corning® glass, measuring in at 28-mm diameter x 300 m length. The Y shape branched at an angle of 120, with each branch serving as an arm of the olfactometer. The stem of each Y-tube was 20 cm long. At the bifurcation, each branch extended 4 cm from the junction before ending in 10 cm parallel arms. The Y-tube was positioned horizontally inside a black box made of poster board (46 x 32 x 101.5 cm), designed to prevent the entry of unwanted ambient light. The black box had two holes on the upstream sie of the olfactometer, allowing a fiber optic illuminator (T-Q/FOI-1, Techni Quip Corp, El Segundo, CA) and Teflon tubing to pass through. The fiber optic illuminator was used to deliver light to both arms equally from the center of the bifurcation, while the Teflon tubing connected the VCC to the arms of the Y-tube. One arm of the Y-tube delivered volatiles from the enclosed plant while the other delivered filtered, pure air as a control. The movement of adult WSS is positively phototactic and the horizontally placed Y-tube was positioned such that the light distribution towards both arms was balanced to avoid bias. The arms of the Y-tube were oriented to minimize directional bias and the position of the plants was alternated between runs. 

 A 28-cm wire was used to facilitate parasitoid movement from the unbranched stem of the glass Y-tube to the test junction between the two upper arms. The order of individual test insects from a pool of naïve females was randomly assigned for each bioassay, and test plants were chosen randomly from the greenhouse culture before each experiment. All glassware was cleaned using dish soap and warm water, followed by solvent rinses with acetone and hexane. Cleaned and rinsed glassware was baked at 110C in a glassware oven for 24 hours before use. New plants were used for each experiment. 
	Each individual parasitoid was allowed three minutes to respond to either airstream source. Once a positive response was determined to either source, the trail was ended. If no choice was made after five minutes, the trail was ended and the result was recorded as no response. 
	
	
	




